# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('custom_registration', '0001_initial'), ('custom_registration', '0002_auto_20200310_0923')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(choices=[(b'african_american_and_black', b'African American and black'), (b'american_indian_or_alaska_native', b'American Indian / Alaska Native'), (b'asian', b'Asian'), (b'hispanic_or_latinx', b'Hispanic / Latinx'), (b'native_hawaiian_and_pacific_islander', b'Native Hawaiian and Pacific Islander'), (b'south_asian_or_north_african', b'Southwest Asia / North African'), (b'white', b'White'), (b'decline_to_state', b'Decline To State')], max_length=200, verbose_name=b'Ethncity')),
                ('age', models.CharField(choices=[(b'13_to_17_years', b'13-17 years old'), (b'18_to_22_years', b'18 - 22 years old'), (b'23_to_29_years', b'23 - 29 years old'), (b'30_to_49_years', b'30 - 49 years old'), (b'50_above_years old', b'50 + years old'), (b'decline_to_state', b'Decline To State')], max_length=200, verbose_name=b'Age')),
                ('resource', models.CharField(blank=True, choices=[(b'13_to_17_years', b'Social Media'), (b'18_to_22_years', b'Email'), (b'23_to_29_years', b'Word-of-Mouth'), (b'30_to_49_years', b'Print Advertisemen'), (b'50_above_years old', b'Other')], max_length=200, null=True, verbose_name=b'How did you hear about UC San Diego _Online_?')),
                ('gender', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female'), (b'non-binary', b'Non-Binary'), (b'decline_to_state', b'Decline To State')], max_length=200, verbose_name=b'Gender')),
                ('highest_level_of_education', models.CharField(choices=[(b'graduate', b'Graduate'), (b'un_graduate', b'Undergraduate'), (b'high_school', b'Up to High School'), (b'decline_to_state', b'Decline To State')], max_length=200, verbose_name=b'Highest level of education completed')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
