# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedprofile',
            name='resource',
            field=models.CharField(blank=True, choices=[(b'13_to_17_years', b'Social Media'), (b'18_to_22_years', b'Email'), (b'23_to_29_years', b'Word-of-Mouth'), (b'30_to_49_years', b'Print Advertisemen'), (b'50_above_years old', b'Other')], max_length=200, null=True, verbose_name=b'How did you hear about UC San Diego _Online_?'),
        ),
    ]
